In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.options.display.max_columns = None

In [3]:
df_orignal = pd.read_csv('Time-Wasters on Social Media.csv')

In [4]:
df = df_orignal.copy()

In [5]:
df

,UserID,Age,Gender,Location,Income,Debt,Owns Property,Profession,Demographics,Platform,Total Time Spent,Number of Sessions,Video ID,Video Category,Video Length,Engagement,Importance Score,Time Spent On Video,Number of Videos Watched,Scroll Rate,Frequency,ProductivityLoss,Satisfaction,Watch Reason,DeviceType,OS,Watch Time,Self Control,Addiction Level,CurrentActivity,ConnectionType
0,1,56,Male,Pakistan,82812,True,True,Engineer,Rural,Instagram,80,17,4229,Pranks,24,7867,5,26,22,87,Night,3,7,Procrastination,Smartphone,Android,9:00 PM,5,5,Commuting,Mobile Data
1,2,46,Female,Mexico,27999,False,True,Artist,Urban,Instagram,228,14,2131,Pranks,19,5944,6,25,31,46,Afternoon,5,5,Habit,Computer,Android,5:00 PM,7,3,At school,Wi-Fi
2,3,32,Female,United States,42436,False,True,Engineer,Rural,Facebook,30,6,4367,Vlogs,19,8674,3,9,7,88,Evening,6,4,Entertainment,Tablet,Android,2:00 PM,8,2,At home,Mobile Data
3,4,60,Male,Barzil,62963,True,False,Waiting staff,Rural,YouTube,101,19,1507,Vlogs,4,2477,2,6,41,93,Night,3,7,Habit,Smartphone,Android,9:00 PM,5,5,Commuting,Mobile Data
4,5,25,Male,Pakistan,22096,False,True,Manager,Urban,TikTok,136,6,2159,Gaming,19,3093,7,13,21,4,Morning,8,2,Boredom,Smartphone,iOS,8:00 AM,10,0,At home,Mobile Data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,22,Male,India,74254,True,True,Students,Rural,TikTok,144,7,6168,Gaming,1,5179,6,17,17,47,Afternoon,9,1,Procrastination,Smartphone,iOS,5:45 PM,10,0,At work,Mobile Data
996,997,40,Female,Pakistan,27006,False,False,Waiting staff,Urban,Facebook,231,15,2794,Life Hacks,2,1803,4,2,17,15,Night,8,2,Boredom,Smartphone,MacOS,10:15 PM,10,0,At home,Mobile Data
997,998,27,Male,India,94218,True,True,Waiting staff,Rural,TikTok,165,1,2893,Pranks,12,9290,3,9,28,44,Night,9,1,Procrastination,Smartphone,iOS,10:15 PM,10,0,Commuting,Mobile Data
998,999,61,Male,Pakistan,85344,True,False,Students,Urban,YouTube,151,11,1199,Life Hacks,15,2050,5,12,30,62,Night,3,7,Procrastination,Smartphone,MacOS,10:15 PM,5,5,At work,Wi-Fi
999,1000,19,Male,India,53840,True,True,driver,Urban,YouTube,167,17,8012,Pranks,4,9790,3,19,40,6,Evening,6,4,Procrastination,Smartphone,Android,4:25 PM,8,2,At home,Mobile Data

In [6]:
df.drop(columns=['Demographics','Income','Profession','CurrentActivity','ConnectionType','Video ID','UserID','OS','DeviceType','Importance Score','Scroll Rate','Number of Sessions','Number of Videos Watched'],inplace=True)

In [7]:
df.drop(columns=['Video Length','Time Spent On Video'],inplace=True)

In [8]:
df

,Age,Gender,Location,Debt,Owns Property,Platform,Total Time Spent,Video Category,Engagement,Frequency,ProductivityLoss,Satisfaction,Watch Reason,Watch Time,Self Control,Addiction Level
0,56,Male,Pakistan,True,True,Instagram,80,Pranks,7867,Night,3,7,Procrastination,9:00 PM,5,5
1,46,Female,Mexico,False,True,Instagram,228,Pranks,5944,Afternoon,5,5,Habit,5:00 PM,7,3
2,32,Female,United States,False,True,Facebook,30,Vlogs,8674,Evening,6,4,Entertainment,2:00 PM,8,2
3,60,Male,Barzil,True,False,YouTube,101,Vlogs,2477,Night,3,7,Habit,9:00 PM,5,5
4,25,Male,Pakistan,False,True,TikTok,136,Gaming,3093,Morning,8,2,Boredom,8:00 AM,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,Male,India,True,True,TikTok,144,Gaming,5179,Afternoon,9,1,Procrastination,5:45 PM,10,0
996,40,Female,Pakistan,False,False,Facebook,231,Life Hacks,1803,Night,8,2,Boredom,10:15 PM,10,0
997,27,Male,India,True,True,TikTok,165,Pranks,9290,Night,9,1,Procrastination,10:15 PM,10,0
998,61,Male,Pakistan,True,False,YouTube,151,Life Hacks,2050,Night,3,7,Procrastination,10:15 PM,5,5
999,19,Male,India,True,True,YouTube,167,Pranks,9790,Evening,6,4,Procrastination,4:25 PM,8,2

In [9]:
temp_df = df.copy()

In [10]:
df['Addiction Level'].value_counts()

Addiction Level
2    248
5    228
0    180
3    159
1     60
7     55
4     36
6     34
Name: count, dtype: int64

In [11]:
df['Addiction Level'] = df['Addiction Level'].replace({0: 'no addiction', 1: 'low',
                                                     2: 'low', 3: 'moderate', 4: 'moderate',
                                                     5: 'high', 6: 'high', 7: 'extreme'})

In [12]:
df['Addiction Level'].value_counts()

Addiction Level
low             308
high            262
moderate        195
no addiction    180
extreme          55
Name: count, dtype: int64

In [13]:
df['Total Time Spent'].describe()

count    1000.000000
mean      151.406000
std        83.952637
min        10.000000
25%        78.000000
50%       152.000000
75%       223.000000
max       298.000000
Name: Total Time Spent, dtype: float64

In [14]:
temp_df = temp_df.select_dtypes(exclude=['object','bool'])

In [15]:
temp_df.corr()['Addiction Level']

Age                 0.033493
Total Time Spent    0.016086
Engagement          0.027620
ProductivityLoss   -0.994939
Satisfaction        0.994939
Self Control       -1.000000
Addiction Level     1.000000
Name: Addiction Level, dtype: float64

In [16]:
df

,Age,Gender,Location,Debt,Owns Property,Platform,Total Time Spent,Video Category,Engagement,Frequency,ProductivityLoss,Satisfaction,Watch Reason,Watch Time,Self Control,Addiction Level
0,56,Male,Pakistan,True,True,Instagram,80,Pranks,7867,Night,3,7,Procrastination,9:00 PM,5,high
1,46,Female,Mexico,False,True,Instagram,228,Pranks,5944,Afternoon,5,5,Habit,5:00 PM,7,moderate
2,32,Female,United States,False,True,Facebook,30,Vlogs,8674,Evening,6,4,Entertainment,2:00 PM,8,low
3,60,Male,Barzil,True,False,YouTube,101,Vlogs,2477,Night,3,7,Habit,9:00 PM,5,high
4,25,Male,Pakistan,False,True,TikTok,136,Gaming,3093,Morning,8,2,Boredom,8:00 AM,10,no addiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,Male,India,True,True,TikTok,144,Gaming,5179,Afternoon,9,1,Procrastination,5:45 PM,10,no addiction
996,40,Female,Pakistan,False,False,Facebook,231,Life Hacks,1803,Night,8,2,Boredom,10:15 PM,10,no addiction
997,27,Male,India,True,True,TikTok,165,Pranks,9290,Night,9,1,Procrastination,10:15 PM,10,no addiction
998,61,Male,Pakistan,True,False,YouTube,151,Life Hacks,2050,Night,3,7,Procrastination,10:15 PM,5,high
999,19,Male,India,True,True,YouTube,167,Pranks,9790,Evening,6,4,Procrastination,4:25 PM,8,low

In [17]:
lower = df['Total Time Spent'].quantile(.33)
medium = df['Total Time Spent'].quantile(.66)
higher = df['Total Time Spent'].quantile(1)

In [18]:
higher,lower,medium

(298.0, 101.0, 197.0)

In [19]:
def convert(time):
    if time<=101:
        return 'less'
    elif 101<time<=197:
        return 'moderate'
    elif 197<time<=298:
        return 'high'
    else:
        return None

In [20]:
df['Total Time Spent'] = df['Total Time Spent'].apply(convert)

In [21]:
df['Total Time Spent'].value_counts()

Total Time Spent
high        336
less        334
moderate    330
Name: count, dtype: int64

In [22]:
df

,Age,Gender,Location,Debt,Owns Property,Platform,Total Time Spent,Video Category,Engagement,Frequency,ProductivityLoss,Satisfaction,Watch Reason,Watch Time,Self Control,Addiction Level
0,56,Male,Pakistan,True,True,Instagram,less,Pranks,7867,Night,3,7,Procrastination,9:00 PM,5,high
1,46,Female,Mexico,False,True,Instagram,high,Pranks,5944,Afternoon,5,5,Habit,5:00 PM,7,moderate
2,32,Female,United States,False,True,Facebook,less,Vlogs,8674,Evening,6,4,Entertainment,2:00 PM,8,low
3,60,Male,Barzil,True,False,YouTube,less,Vlogs,2477,Night,3,7,Habit,9:00 PM,5,high
4,25,Male,Pakistan,False,True,TikTok,moderate,Gaming,3093,Morning,8,2,Boredom,8:00 AM,10,no addiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,Male,India,True,True,TikTok,moderate,Gaming,5179,Afternoon,9,1,Procrastination,5:45 PM,10,no addiction
996,40,Female,Pakistan,False,False,Facebook,high,Life Hacks,1803,Night,8,2,Boredom,10:15 PM,10,no addiction
997,27,Male,India,True,True,TikTok,moderate,Pranks,9290,Night,9,1,Procrastination,10:15 PM,10,no addiction
998,61,Male,Pakistan,True,False,YouTube,moderate,Life Hacks,2050,Night,3,7,Procrastination,10:15 PM,5,high
999,19,Male,India,True,True,YouTube,moderate,Pranks,9790,Evening,6,4,Procrastination,4:25 PM,8,low

In [23]:
df['Engagement'].describe()

count    1000.000000
mean     4997.159000
std      2910.053701
min        15.000000
25%      2415.750000
50%      5016.000000
75%      7540.250000
max      9982.000000
Name: Engagement, dtype: float64

In [24]:
def convert1(num):
    if num<=3000:
        return 'less'
    elif 3000<num<=6000:
        return 'moderate'
    elif 6000<num<=9982:
        return 'high'
    else:
        return None

In [25]:
df['Engagement'] = df['Engagement'].apply(convert1)

In [26]:
df['Engagement'].value_counts()

Engagement
high        403
less        306
moderate    291
Name: count, dtype: int64

In [28]:
from sklearn.preprocessing import OrdinalEncoder

# Create a copy of the original data for label encoding
data_label_encoded = df.copy()

categorical_cols = df.select_dtypes(include=['object','bool']).columns

# Apply label encoding to categorical columns
for col in categorical_cols:
    oe = OrdinalEncoder()
    data_label_encoded[col] = oe.fit_transform(data_label_encoded[[col]])
    
# Splitting the dataset into training and testing sets
X_label = data_label_encoded.drop('Addiction Level', axis=1)
y_label = data_label_encoded['Addiction Level']

In [29]:
X_label

,Age,Gender,Location,Debt,Owns Property,Platform,Total Time Spent,Video Category,Engagement,Frequency,ProductivityLoss,Satisfaction,Watch Reason,Watch Time,Self Control
0,56,1.0,6.0,1.0,1.0,1.0,1.0,6.0,0.0,3.0,3,7,3.0,13.0,5
1,46,0.0,5.0,0.0,1.0,1.0,0.0,6.0,2.0,0.0,5,5,2.0,6.0,7
2,32,0.0,8.0,0.0,1.0,0.0,1.0,8.0,0.0,1.0,6,4,1.0,2.0,8
3,60,1.0,0.0,1.0,0.0,3.0,1.0,8.0,1.0,3.0,3,7,2.0,13.0,5
4,25,1.0,6.0,0.0,1.0,2.0,2.0,3.0,2.0,2.0,8,2,0.0,11.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,1.0,2.0,1.0,1.0,2.0,2.0,3.0,2.0,0.0,9,1,3.0,7.0,10
996,40,0.0,6.0,0.0,0.0,0.0,0.0,5.0,1.0,3.0,8,2,0.0,0.0,10
997,27,1.0,2.0,1.0,1.0,2.0,2.0,6.0,0.0,3.0,9,1,3.0,0.0,10
998,61,1.0,6.0,1.0,0.0,3.0,2.0,5.0,1.0,3.0,3,7,3.0,0.0,5
999,19,1.0,2.0,1.0,1.0,3.0,2.0,6.0,0.0,1.0,6,4,3.0,5.0,8

In [47]:
df.to_csv('df.csv',index=False)